### ISSUE TITLE
Zertifikat nicht mehr gültig (?)

### ISSUE THREAD

**Issue by DavAlbert** [kanonenfutter/njodel#1]
Moin, ich vermute, dass das Zertifikat nicht mehr gültig ist.
Das ist meine Ausgabe bei der Erstellung eines Nutzerkontos:

```
Latitude: 50.937531 Longitude: 6.960279 City: Cologne
Creating new account.
Traceback (most recent call last):
  File "python/jodel.py", line 27, in <module>
    j = jodel_api.JodelAccount(lat=lat, lng=lng, city=city, is_legacy=False)
  File "/usr/local/lib/python3.7/site-packages/jodel_api/jodel_api.py", line 56, in __init__
    r = self.refresh_all_tokens(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/jodel_api/jodel_api.py", line 136, in refresh_all_tokens
    raise Exception(resp)
Exception: (477, {'error': 'Signed request expected', 'metadata': None})
```

**Comment by DavAlbert** [comment]
Okay, das Projekt wurde vor 2 Jahren gebaut. lol :D

**Comment by kanonenfutter** [comment]
@DavAlbert Jep, das Projekt wird leider nicht mehr maintained. Das zugrunde liegende Interface ebenso nicht. https://github.com/nborrmann/jodel_api
